//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contramcamlamroi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category
    {
        [NotMapped]
        public List<Category> ListCate { get; set; }

        public Category()
        {
            this.Products = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string IDCate { get; set; }
        public string NameCate { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}
